### ISSUE TITLE
Upstream Nestopia UE is at version 1.49, the current 1.46.2 is from 4 years ago

### ISSUE THREAD

**Issue by yetisyny** [OpenEmu/Nestopia-Core#3]
See [https://github.com/0ldsk00l/nestopia/releases](https://github.com/0ldsk00l/nestopia/releases). Upstream, Nestopia UE has had a 1.49 release. You are still working with their old release 1.46.2 from 4 years ago in 2014. Please update to Nestopia UE 1.49. The libretro port at [https://github.com/libretro/nestopia](https://github.com/libretro/nestopia) is even with Nestopia UE and also has a 1.49 release too. I understand that you use a different system from libretro for OpenEmu cores, called OEGameCore, but it ought to be possible to update to the latest Nestopia UE release. This would bring 4 years’ worth of improvements to the Nestopia core in OpenEmu.

**Comment by clobber** [comment]
lol... we know all about that and already have many mapper bug fixes merged from the repo.

Thanks for coming out!
