### ISSUE TITLE
Support up to four players in Micro Mages

### ISSUE THREAD

**Issue by troyjfarrell** [OpenEmu/Nestopia-Core#6]
I have discovered that [Micro Mages](http://morphcat.de/micromages/) supports up to four players using Nestopia for Windows.  I would like to have this support in OpenEmu.  I am happy to work on this but I don't know where to start.

**Comment by MaddTheSane** [comment]
My guess is editing/updating `NstDatabase.xml` to include Micro Mages.

**Comment by troyjfarrell** [comment]
Thanks!  It took me a while to sort out the right incantations for `NstDatabase.xml`.

It seems that @adam-becker was really close in https://github.com/0ldsk00l/nestopia/issues/348.  The right answer is
```xml
    <game>
        <peripherals>
            <device type="fourplayer" />
        </peripherals>
        <cartridge system="NES-NTSC" dump="ok" crc="4E6B9078" sha1="93FF8CEC778771C7200F785798E0D1599EE8FEB5">
            <board type="NES-NROM-256" mapper="0">
                <prg size="32k" />
                <chr size="8k" />
                <pad h="0" v="1" />
            </board>
        </cartridge>
    </game>
```

If we can add this to `NstDatabase.xml`, I'll put together a PR.

**Comment by clobber** [comment]
There is no need for a Pull Request. This has already been addressed [upstream](https://gitlab.com/jgemu/nestopia), so it will be available in our core port once I sync and push a release.

**Comment by troyjfarrell** [comment]
Great!

By the way, is that upstream documented somewhere?  I spent hours looking for it.  I only found https://github.com/0ldsk00l/nestopia, which appears to be upstream for libretro.

**Comment by clobber** [comment]
Resolved in the latest core port release of Nestopia.
